const actionTypes = {
  LOG_IN: "LOG_IN",
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  LOG_IN_FAILED: "LOG_IN_FAILED",
  LOADING: "LOADING",
  SEARCH_ITEMS: "REQUEST_ITEMS",
  SEARCH_ITEMS_SUCCESS: "SEARCH_ITEMS_SUCCESS",
  SEARCH_ITEMS_FAILED: "SEARCH_ITEMS_FAILED",
};

export default actionTypes;
